spring.application.name=mycoolapp
info.app.description=A crazy fun app, yoohoo!
info.app.version=1.0.0

#Actuator Properties
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

#management.endpoints.web.exposure.exclude=health,info

#security properties
spring.security.user.name=user
spring.security.user.password=boot


#Define custom properties
coach.name=Mickey Mouse
team.name=The Mouse Club


#Log Levels severity mapping: Core
logging.level.org.springframework=DEBUG
logging.level.org.hiberate=TRACE
logging.level.com.luv2code=INFO

#Web properties
server.port = 7070
server.servlet.context-path=/mycoolapp
