spring.application.name=mycoolapp
info.app.description=A crazy fun app, yoohoo!
info.app.version=1.0.0

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

#management.endpoints.web.exposure.exclude=health,info

spring.security.user.name=user
spring.security.user.password=boot